name: Build & Release

on:
  push:
    tags: [ '*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.3.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Save to CHANGELOG
        run: echo "${{ steps.changelog.outputs.changelog }}" > CHANGELOG.md

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./target/VarBlocks*.jar
            CHANGELOG.md

      - name: GH Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          fail_on_unmatched_files: true
          files: "./target/VarBlocks*.jar"
          draft: false
          prerelease: false